### ISSUE TITLE
Feature : Implementing a dark mode/theme for Training documentation and the official documentaiton of Plone

### ISSUE THREAD

**Issue by rakshith6404** [plone/training#735] opened 2023-03-09 11:53 UTC
@heyy stevepiercy , 

I am thinking of adding dark theme for the training documentation for both Training and the official [Documentation](https://6.docs.plone.org/index.html) of Plone as i was going through the documentation of [RESTAPI](https://plonerestapi.readthedocs.io/en/latest/) , i found it useful which could help improve visual ergonomics by reducing eye strain apart, especially in low light environments. :new_moon_with_face: :full_moon_with_face: and would like to implement it in this training documentation also.
Looking forward for your review and response for the same.Looking for a response.

The documentation in RESTAPI , when switched to dark mode does not make the codes or the code snippet visible.

![Screencast from 09-03-23 05_17_07 PM IST](https://user-images.githubusercontent.com/92712034/224015350-72fec56c-fa5e-4240-aae4-f86e73037191.gif)

**Comment by stevepiercy** [comment] 2023-03-09 21:04
Closing as duplicate of https://github.com/plone/training/issues/533

Please see that issue for the plan. Thank you.

**Closed by stevepiercy** 2023-03-09 21:04 UTC
